# Generated by Django 3.0.3 on 2020-02-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tfgame',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('company', models.CharField(max_length=30, verbose_name='company')),
                ('price', models.CharField(max_length=30, verbose_name='price')),
                ('os', models.CharField(max_length=30, verbose_name='os')),
                ('release', models.CharField(max_length=50, verbose_name='release')),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임',
                'db_table': 'toffy_game',
            },
        ),
    ]
