# Generated by Django 3.0.2 on 2020-02-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfgame',
            name='image',
            field=models.CharField(default='SOME STRING', max_length=300, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='tfgame',
            name='rank',
            field=models.CharField(default='SOME STRING', max_length=30, verbose_name='rank'),
        ),
    ]
