# Generated by Django 3.0.2 on 2020-04-30 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0002_auto_20200215_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tfgame',
            old_name='os',
            new_name='href',
        ),
        migrations.RemoveField(
            model_name='tfgame',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tfgame',
            name='release',
        ),
    ]
