# Generated by Django 3.0.3 on 2020-05-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0003_auto_20200430_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfgame',
            name='href',
            field=models.CharField(max_length=300, verbose_name='href'),
        ),
    ]
