# Generated by Django 3.0.3 on 2020-05-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0004_auto_20200516_1518'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='tfgame',
        #     name='tag1',
        # ),
        # migrations.RemoveField(
        #     model_name='tfgame',
        #     name='tag2',
        # ),
        # migrations.RemoveField(
        #     model_name='tfgame',
        #     name='tag3',
        # ),
    ]
