# Generated by Django 3.0.2 on 2020-05-17 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0005_auto_20200516_1724'),
    ]

    operations = [
        
    ]
