# Generated by Django 3.0.2 on 2020-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0006_tfgame_num'),
    ]

    operations = [
        
    ]
