# Generated by Django 3.0.3 on 2020-05-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0007_auto_20200517_1130'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfgame',
            options={'managed': False, 'verbose_name': '게임', 'verbose_name_plural': '게임'},
        ),
    ]
