# Generated by Django 3.0.3 on 2020-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0008_auto_20200518_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfgame',
            options={'managed': False, 'verbose_name': '게임', 'verbose_name_plural': '게임'},
        ),
    ]
