# Generated by Django 3.0.3 on 2020-05-20 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0010_auto_20200518_2315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tfgame',
            options={'verbose_name': '게임', 'verbose_name_plural': '게임'},
        ),
    ]
