# Generated by Django 3.0.3 on 2020-05-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0011_auto_20200520_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfgame',
            name='tag1',
            field=models.CharField(default='0', max_length=2, verbose_name='tag1'),
        ),
        migrations.AddField(
            model_name='tfgame',
            name='tag2',
            field=models.CharField(default='0', max_length=2, verbose_name='tag2'),
        ),
        migrations.AddField(
            model_name='tfgame',
            name='tag3',
            field=models.CharField(default='0', max_length=2, verbose_name='tag3'),
        ),
        migrations.AlterField(
            model_name='tfgame',
            name='price',
            field=models.CharField(max_length=7, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='tfgame',
            name='rank',
            field=models.CharField(max_length=4, verbose_name='rank'),
        ),
    ]
