# Generated by Django 3.0.3 on 2020-05-24 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfgame', '0012_auto_20200520_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='tfgame',
            name='tag4',
            field=models.CharField(default='0', max_length=2, verbose_name='tag4'),
        ),
        migrations.AddField(
            model_name='tfgame',
            name='tag5',
            field=models.CharField(default='0', max_length=2, verbose_name='tag5'),
        ),
    ]
