# Generated by Django 3.0.3 on 2020-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tftag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=25, verbose_name='action')),
                ('arcade', models.CharField(max_length=25, verbose_name='arcade')),
                ('indie', models.CharField(max_length=25, verbose_name='indie')),
                ('casual', models.CharField(max_length=25, verbose_name='casual')),
                ('adventure', models.CharField(max_length=25, verbose_name='adventure')),
                ('simulation', models.CharField(max_length=25, verbose_name='simulation')),
                ('strategy', models.CharField(max_length=25, verbose_name='strategy')),
                ('roleplay', models.CharField(max_length=25, verbose_name='roleplay')),
                ('sports', models.CharField(max_length=25, verbose_name='sports')),
                ('horror', models.CharField(max_length=25, verbose_name='horror')),
                ('pixel', models.CharField(max_length=25, verbose_name='pixel')),
                ('puzzle', models.CharField(max_length=25, verbose_name='puzzle')),
                ('story', models.CharField(max_length=25, verbose_name='story')),
                ('fantasy', models.CharField(max_length=25, verbose_name='fantasy')),
                ('shooting', models.CharField(max_length=25, verbose_name='shooting')),
                ('survival', models.CharField(max_length=25, verbose_name='survival')),
                ('fps', models.CharField(max_length=25, verbose_name='fps')),
                ('explorer', models.CharField(max_length=25, verbose_name='explorer')),
                ('cute', models.CharField(max_length=25, verbose_name='cute')),
                ('movie', models.CharField(max_length=25, verbose_name='movie')),
                ('zombie', models.CharField(max_length=25, verbose_name='zombie')),
                ('dark', models.CharField(max_length=25, verbose_name='dark')),
                ('mystery', models.CharField(max_length=25, verbose_name='mystery')),
                ('structure', models.CharField(max_length=25, verbose_name='structure')),
                ('management', models.CharField(max_length=25, verbose_name='management')),
                ('act_adventure', models.CharField(max_length=25, verbose_name='act_adventure')),
                ('act_roleplay', models.CharField(max_length=25, verbose_name='act_roleplay')),
                ('war', models.CharField(max_length=25, verbose_name='war')),
                ('music', models.CharField(max_length=25, verbose_name='music')),
                ('rom_simulation', models.CharField(max_length=25, verbose_name='rom_simulation')),
                ('post_apocalypse', models.CharField(max_length=25, verbose_name='post_apocalypse')),
                ('addictive', models.CharField(max_length=25, verbose_name='addictive')),
                ('beautiful', models.CharField(max_length=25, verbose_name='beautiful')),
                ('romance', models.CharField(max_length=25, verbose_name='romance')),
                ('wizard', models.CharField(max_length=25, verbose_name='wizard')),
                ('cards', models.CharField(max_length=25, verbose_name='cards')),
                ('worldwar', models.CharField(max_length=25, verbose_name='worldwar')),
                ('racing', models.CharField(max_length=25, verbose_name='racing')),
                ('thriller', models.CharField(max_length=25, verbose_name='thriller')),
                ('flight', models.CharField(max_length=25, verbose_name='flight')),
                ('rhythm', models.CharField(max_length=25, verbose_name='rhythm')),
                ('philosophy', models.CharField(max_length=25, verbose_name='philosophy')),
                ('timeslip', models.CharField(max_length=25, verbose_name='timeslip')),
                ('cat', models.CharField(max_length=25, verbose_name='cat')),
                ('dog', models.CharField(max_length=25, verbose_name='dog')),
                ('soccer', models.CharField(max_length=25, verbose_name='soccer')),
                ('fishing', models.CharField(max_length=25, verbose_name='fishing')),
                ('bike', models.CharField(max_length=25, verbose_name='bike')),
                ('golf', models.CharField(max_length=25, verbose_name='golf')),
                ('pocketball', models.CharField(max_length=25, verbose_name='pocketball')),
            ],
            options={
                'verbose_name': '태그',
                'verbose_name_plural': '태그',
                'db_table': 'toffy_tag',
            },
        ),
    ]
