# Generated by Django 3.0.3 on 2020-05-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tftag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tftag',
            name='act_adventure',
            field=models.CharField(blank=True, max_length=25, verbose_name='act_adventure'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='act_roleplay',
            field=models.CharField(blank=True, max_length=25, verbose_name='act_roleplay'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='action',
            field=models.CharField(blank=True, max_length=25, verbose_name='action'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='addictive',
            field=models.CharField(blank=True, max_length=25, verbose_name='addictive'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='adventure',
            field=models.CharField(blank=True, max_length=25, verbose_name='adventure'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='arcade',
            field=models.CharField(blank=True, max_length=25, verbose_name='arcade'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='beautiful',
            field=models.CharField(blank=True, max_length=25, verbose_name='beautiful'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='bike',
            field=models.CharField(blank=True, max_length=25, verbose_name='bike'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='cards',
            field=models.CharField(blank=True, max_length=25, verbose_name='cards'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='casual',
            field=models.CharField(blank=True, max_length=25, verbose_name='casual'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='cat',
            field=models.CharField(blank=True, max_length=25, verbose_name='cat'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='cute',
            field=models.CharField(blank=True, max_length=25, verbose_name='cute'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='dark',
            field=models.CharField(blank=True, max_length=25, verbose_name='dark'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='dog',
            field=models.CharField(blank=True, max_length=25, verbose_name='dog'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='explorer',
            field=models.CharField(blank=True, max_length=25, verbose_name='explorer'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='fantasy',
            field=models.CharField(blank=True, max_length=25, verbose_name='fantasy'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='fishing',
            field=models.CharField(blank=True, max_length=25, verbose_name='fishing'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='flight',
            field=models.CharField(blank=True, max_length=25, verbose_name='flight'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='fps',
            field=models.CharField(blank=True, max_length=25, verbose_name='fps'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='golf',
            field=models.CharField(blank=True, max_length=25, verbose_name='golf'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='horror',
            field=models.CharField(blank=True, max_length=25, verbose_name='horror'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='indie',
            field=models.CharField(blank=True, max_length=25, verbose_name='indie'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='management',
            field=models.CharField(blank=True, max_length=25, verbose_name='management'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='movie',
            field=models.CharField(blank=True, max_length=25, verbose_name='movie'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='music',
            field=models.CharField(blank=True, max_length=25, verbose_name='music'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='mystery',
            field=models.CharField(blank=True, max_length=25, verbose_name='mystery'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='philosophy',
            field=models.CharField(blank=True, max_length=25, verbose_name='philosophy'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='pixel',
            field=models.CharField(blank=True, max_length=25, verbose_name='pixel'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='pocketball',
            field=models.CharField(blank=True, max_length=25, verbose_name='pocketball'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='post_apocalypse',
            field=models.CharField(blank=True, max_length=25, verbose_name='post_apocalypse'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='puzzle',
            field=models.CharField(blank=True, max_length=25, verbose_name='puzzle'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='racing',
            field=models.CharField(blank=True, max_length=25, verbose_name='racing'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='rhythm',
            field=models.CharField(blank=True, max_length=25, verbose_name='rhythm'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='roleplay',
            field=models.CharField(blank=True, max_length=25, verbose_name='roleplay'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='rom_simulation',
            field=models.CharField(blank=True, max_length=25, verbose_name='rom_simulation'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='romance',
            field=models.CharField(blank=True, max_length=25, verbose_name='romance'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='shooting',
            field=models.CharField(blank=True, max_length=25, verbose_name='shooting'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='simulation',
            field=models.CharField(blank=True, max_length=25, verbose_name='simulation'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='soccer',
            field=models.CharField(blank=True, max_length=25, verbose_name='soccer'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='sports',
            field=models.CharField(blank=True, max_length=25, verbose_name='sports'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='story',
            field=models.CharField(blank=True, max_length=25, verbose_name='story'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='strategy',
            field=models.CharField(blank=True, max_length=25, verbose_name='strategy'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='structure',
            field=models.CharField(blank=True, max_length=25, verbose_name='structure'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='survival',
            field=models.CharField(blank=True, max_length=25, verbose_name='survival'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='thriller',
            field=models.CharField(blank=True, max_length=25, verbose_name='thriller'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='timeslip',
            field=models.CharField(blank=True, max_length=25, verbose_name='timeslip'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='war',
            field=models.CharField(blank=True, max_length=25, verbose_name='war'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='wizard',
            field=models.CharField(blank=True, max_length=25, verbose_name='wizard'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='worldwar',
            field=models.CharField(blank=True, max_length=25, verbose_name='worldwar'),
        ),
        migrations.AlterField(
            model_name='tftag',
            name='zombie',
            field=models.CharField(blank=True, max_length=25, verbose_name='zombie'),
        ),
    ]
