# Generated by Django 3.0.3 on 2020-05-18 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tftag', '0003_auto_20200518_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tftag',
            options={'managed': True, 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
    ]
