# Generated by Django 3.0.3 on 2020-05-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tftag', '0004_auto_20200518_2254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tftag',
            options={'managed': False, 'verbose_name': '태그', 'verbose_name_plural': '태그'},
        ),
    ]
