# Generated by Django 3.0.3 on 2020-05-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tftag', '0005_auto_20200518_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfgame',
            fields=[
                ('num', models.CharField(default='SOME STRING', max_length=30, primary_key=True, serialize=False, verbose_name='rank')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('price', models.CharField(max_length=30, verbose_name='price')),
                ('href', models.CharField(max_length=30, verbose_name='href')),
                ('image', models.CharField(default='SOME STRING', max_length=100, verbose_name='image')),
                ('rank', models.CharField(default='SOME STRING', max_length=30, verbose_name='rank')),
            ],
            options={
                'verbose_name': '게임',
                'verbose_name_plural': '게임',
                'db_table': 'toffy_game',
                'managed': False,
            },
        ),
    ]
