# Generated by Django 3.0.3 on 2020-05-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tftag', '0006_tfgame'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tfgame',
        ),
    ]
